name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'
      - name: Install dependencies
        run: |
          python -m pip install uv==0.6.3
          uv pip install -e ".[lint]" --system
      - name: Ruff
        run: ruff check --fix
      - name: Format
        run: ruff format
